name: E2E Tests

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-run-e2e-tests
  cancel-in-progress: true

jobs:
  e2e_tests:
    name: Run E2E Tests
    # only run if the review is approved, or if its a commit to `main`
    if: github.event.review.state == 'APPROVED' || github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node Modules
        run: yarn install

      - name: Print Dummy Secret
        run: echo ${{ secrets.DUMMY_SECRET }}

      - name: Run Tests
        run: yarn test

      - name: Publish Results
        uses: dorny/test-reporter@v1
        id: test-reporter
        if: success() || failure() # run this step even if previous step failed
        with:
          name: E2E Test Report
          only-summary: 'false'
          list-suites: 'all'
          list-tests: 'all'
          fail-on-error: 'true'
          reporter: 'jest-junit'
          path: |
            junit.xml

        # TODO: Add PR Comment
      - name: Add PR Comment
        run: |
          echo ${{steps.test-reporter.outputs.url_html}}
